### ISSUE TITLE
Booting new world open source Linux ditro on 3A5000-7A2000-EVB

### ISSUE THREAD

**Issue by mikhailnov** [loongson/Firmware#23] opened 2023-01-29 21:45 UTC
Hello chinese friends!

I have motherboard 3A5000-7A2000-EVB v1.5 with UEFI (BIOS) firmware Loongson-UDK2018-V2.0.05269-beta8 which seems to be much older than DK2018_3A5000-7A2000_Desktop_EVB_V4.0.05383-beta10_dbg.fd in this repository.
https://linux-hardware.org/?probe=2fea9476f5

I have successfully booted and installed Loongnix 20. It is an "old world" Linux distribution built with non-upstream toolchain. This article https://blog.xen0n.name/en/posts/tinkering/loongarch-faq and https://lpc.events/event/16/contributions/1178/attachments/1000/1948/lpc2022-loongarch-20220913.pdf say about new and old worlds. Now I want to boot an open source new world Linux distro built with upstream toolchain (gcc, binutils). But I cannot boot any of them.

First, I tried to boot LiveCDs , e.g. https://github.com/fedora-remix-loongarch/releases-info , in virt-manager (qemu) which is preinstalled in Loongnix and got "cannot allocate memory for memory map"

I tried to add initrd+vmlinuz from them into Loognix's Grub bootloader. It froze when trying to load them.

Then I tried to replace `/boot/efi/EFI/*/grub*.efi` with Grub EFI binary from a new world LiveCD and got the same error, now on the real machine:
![image](https://user-images.githubusercontent.com/15802528/215357073-cee76f36-e45a-442f-b8a3-765534de918e.png)

The only thing that comes to mind is that this UEFI (BIOS) version does not support new ISA/ABI (how to name it correctly?).
There is no "Security" page in the UEFI, so updating via a EFI shell will probably be the only option. But I am afraid to brick the motherboard.

Could you please comment if updating firmware is the right solution to run new world LoongArch binaries?
Thanks)

**Comment by mikhailnov** [comment] 2023-01-29 22:34
After studying https://lpc.events/event/16/contributions/1178/attachments/1000/1948/lpc2022-loongarch-20220913.pdf I am pretty sure that UEFI firmware will be updated, but will the new formware from this repository be able to boot both old and new world Linux distributions (e.g. both Loongnix 20 and Fedora)?

**Comment by MarsDoge** [comment] 2023-01-30 01:20
> After studying https://lpc.events/event/16/contributions/1178/attachments/1000/1948/lpc2022-loongarch-20220913.pdf I am pretty sure that UEFI firmware must be updated, but will the new formware from this repository be able to boot both old and new world Linux distributions (e.g. both Loongnix 20 and Fedora)?

As a description, support for booting an open source "new world" Linux distro does require firmware updates.
The new firmware can be downgraded to support the "old world", but only if this option is turned on under the BIOS interface Advance/Legacy.

**Comment by xen0n** [comment] 2023-01-30 03:31
> The new firmware can be *downgraded* to support the "old world"

Probably you mean just "it can be made to support the old world", a downgrade is not required given you have the boot mode toggle. (I haven't tried out the latest A2101 FW revision myself yet.)

And yes @mikhailnov you should definitely upgrade to the latest revision if it indeed has the boot mode switch, so you can indeed dual-boot both worlds. Newer Loongnix is confirmed to boot on both OW and NW firmware.

**Comment by MarsDoge** [comment] 2023-03-31 10:54
If you have tried successfully, please close this issue, thanks for your attention! @mikhailnov

**Closed** 2023-04-11 09:48 UTC

**Comment by matoro** [comment] 2023-07-30 17:01
By the way, I know this is a closed issue, but I would just like to add a note since I ran into this same problem.  The factory firmware can output on either the HDMI port or the VGA port, but the new firmware can ONLY output on the VGA port.  I thought I had screwed up the firmware upgrade, but the problem is that running the new firmware requires a VGA monitor - it will not work on the HDMI port.

**Comment by mikhailnov** [comment] 2024-08-01 14:08
Thanks, upgrading to https://github.com/loongson/Firmware/blob/main/5000Series/PC/3A5000-7A2000-EVB/UDK2018_3A5000-7A2000_Desktop_EVB_V4.0.05569-stable202308_rel.fd has helped, both old world Loongnix and new world ALT Linux boot correctly without any switching in UEFI settings.
@matoro HDMI works ok
